
import pytest
from hypothesis import given, strategies as st
from typing import List, Dict
import sys
import os
from pathlib import Path

# Add backend directory to path
backend_dir = Path(__file__).parent.parent
sys.path.append(str(backend_dir))

from sentence_analysis.word_predictor import PredictionResult
from sentence_analysis.aggregation_engine import AggregationEngine, SentencePrediction

# Strategy for valid emotions
emotion_strategy = st.sampled_from(['angry', 'calm', 'happy', 'sad'])

# Strategy for probabilities that sum to 1.0 (approx)
@st.composite
def probabilities_strategy(draw):
    emotions = ['angry', 'calm', 'happy', 'sad']
    # Draw 4 floats
    raw_probs = draw(st.lists(st.floats(min_value=0.0, max_value=1.0), min_size=4, max_size=4))
    total = sum(raw_probs)
    if total == 0:
        probs = [0.25] * 4
    else:
        probs = [p / total for p in raw_probs]
    
    return {e: p for e, p in zip(emotions, probs)}

# Strategy for PredictionResult
@st.composite
def prediction_result_strategy(draw):
    probs = draw(probabilities_strategy())
    # Determine dominant emotion from probs to be consistent
    dominant = max(probs, key=probs.get)
    confidence = probs[dominant]
    
    return PredictionResult(
        emotion=dominant,
        confidence=confidence,
        probabilities=probs,
        is_uncertain=draw(st.booleans())
    )

class TestWordAnalysisProperties:
    
    @given(st.lists(prediction_result_strategy(), min_size=1))
    def test_word_level_data_structure(self, word_predictions: List[PredictionResult]):
        """
        Property 23: Word-Level Data Structure
        Validates that word-level data structures generated by the pipeline 
        maintain integrity and required fields (emotion, confidence, probabilities).
        """
        aggregator = AggregationEngine()
        
        # We simulate the structure that would be returned by the API's analysis
        # In the actual API, these are converted to dicts/models, 
        # but here we verify the source objects have correct properties
        
        for i, pred in enumerate(word_predictions):
            # 1. Structural Integrity check
            assert isinstance(pred.emotion, str)
            assert pred.emotion in ['angry', 'calm', 'happy', 'sad']
            
            assert isinstance(pred.confidence, float)
            assert 0.0 <= pred.confidence <= 1.0001 # Floating point tolerance
            
            assert isinstance(pred.probabilities, dict)
            assert len(pred.probabilities) == 4
            assert abs(sum(pred.probabilities.values()) - 1.0) < 1e-5
            
            assert isinstance(pred.is_uncertain, bool)
            
            # 2. Consistency check
            # The 'emotion' field should match the key with highest probability
            max_prob_emotion = max(pred.probabilities.items(), key=lambda x: x[1])[0]
            assert pred.emotion == max_prob_emotion
            assert abs(pred.confidence - pred.probabilities[max_prob_emotion]) < 1e-5

    @given(st.lists(prediction_result_strategy(), min_size=2))
    def test_emotion_transition_detection(self, word_predictions: List[PredictionResult]):
        """
        Property 24: Emotion Transition Detection
        Validates that emotion transitions are correctly identified between valid segments.
        """
        # We define a "transition" as a change in the primary emotion between adjacent words
        
        transitions = []
        for i in range(len(word_predictions) - 1):
            current_emotion = word_predictions[i].emotion
            next_emotion = word_predictions[i+1].emotion
            
            if current_emotion != next_emotion:
                transitions.append((i, current_emotion, next_emotion))
        
        # Verify transition logic properties
        
        # 1. If there are no transitions, all emotions must be the same
        if not transitions:
            first_emotion = word_predictions[0].emotion
            for pred in word_predictions:
                assert pred.emotion == first_emotion
        
        # 2. Iterate through detected transitions and verify they are actual changes
        for idx, from_emo, to_emo in transitions:
            assert word_predictions[idx].emotion == from_emo
            assert word_predictions[idx+1].emotion == to_emo
            assert from_emo != to_emo
            
        # 3. Verify that any index NOT in transitions has same emotion as next
        transition_indices = {t[0] for t in transitions}
        for i in range(len(word_predictions) - 1):
            if i not in transition_indices:
                assert word_predictions[i].emotion == word_predictions[i+1].emotion

if __name__ == "__main__":
    pytest.main([__file__])
